# Generated by Django 4.2.6 on 2023-11-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components_amount', models.BigIntegerField()),
            ],
            options={
                'db_table': 'application_components',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField()),
                ('formation_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('price', models.TextField()),
                ('weight', models.BigIntegerField()),
                ('city_production', models.CharField(max_length=100)),
                ('manufacturing_ccompany', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('component_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'components',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=30)),
                ('adress', models.CharField(max_length=400)),
                ('is_moderator', models.BooleanField()),
                ('login', models.CharField(max_length=255)),
                ('passwd', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
